CLASS zcl_refx_CLAIMS_vendor_f4 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_rap_query_provider .

    "Define a local structure and table type for the range
    TYPES: BEGIN OF ty_range_line,
             sign   TYPE c LENGTH 1,
             option TYPE c LENGTH 2,
             low    TYPE string,
             high   TYPE string,
           END OF ty_range_line,
           tt_range_tab TYPE STANDARD TABLE OF ty_range_line WITH EMPTY KEY.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_refx_CLAIMS_vendor_f4 IMPLEMENTATION.


  METHOD if_rap_query_provider~select.

    DATA lt_vendor_range TYPE tt_range_tab.

    " 1. Ensure the request is for data (not just a count)
    IF io_request->is_data_requested( ).

      io_request->get_sort_elements( ).
      io_request->get_paging( ).

      TRY.
**          " 2. Get the filter for 'FIELD' from the UI Binding (constant: 'VENDOR')
**          DATA(lt_filter_cond) = io_request->get_filter( )->get_as_ranges( ).

          " 3. Establish connection via BTP Destination 'refx_gw_ba'
          DATA(lo_dest) = cl_http_destination_provider=>create_by_cloud_destination(
            i_name      = 'refx_gw_ba' ).
*            i_name      = 'refx_gw_pp' ).

          DATA(lo_http_client) = cl_web_http_client_manager=>create_by_http_destination( lo_dest ).

          " 4. Initialize the OData Client Proxy
          DATA(lo_client_proxy) = /iwbep/cl_cp_factory_remote=>create_v2_remote_proxy(
                                  EXPORTING is_proxy_model_key        = VALUE #( repository_id       = 'DEFAULT'
**                                                                                 proxy_model_id      = 'ZREFX_ECC_VENDOR_F4H'
                                                                                 proxy_model_id      = 'ZREFX_ECC_VENDOR_DETAILS'
                                                                                 proxy_model_version = '0001' )
                                            io_http_client            = lo_http_client
                                            iv_relative_service_root  = '/sap/opu/odata/sap/ZREFX_API_CMPCLM_SRV/'
                                           ).

          " 5. Create the Read Request for the specific Entity Set
**          DATA(lo_read_request) = lo_client_proxy->create_resource_for_entity_set( 'F_4_SEARCH_HELP_SET' )->create_request_for_read( ).
          DATA(lo_read_request) = lo_client_proxy->create_resource_for_entity_set( 'VENDOR_DETAILS_SET' )->create_request_for_read( ).
**          " 6. Map the RAP filter to the OData $filter=Field eq 'VENDOR'
**          DATA(lo_filter_factory) = lo_read_request->create_filter_factory( ).
**          " Create a range table manually for the 'Field' property
**          lt_vendor_range = VALUE #( (  sign   = 'I'
**                                        option = 'EQ'
**                                        low    = 'VENDOR' ) ).
**          " Apply this range to the 'Field' property in the OData request
**          DATA(lo_filter) = lo_filter_factory->create_by_range(
**                               iv_property_path = 'FIELD'
**                               it_range         = lt_vendor_range ).
**
**          lo_read_request->set_filter( lo_filter ).

          " 7. Execute the request
          TRY.
              DATA(lo_response) = lo_read_request->execute( ).
            CATCH /iwbep/cx_gateway INTO DATA(lx_gateway).
              " This will often contain the HTML or JSON error from ECC
              DATA(lv_error_text) = lx_gateway->get_text( ).
              " If you are in debug mode, inspect lx_gateway->http_status_code
          ENDTRY.
          " 8. Retrieve and Map the results
          " Use the internal structure type generated by your SCM for 'F4SearchHelpSet'
**          DATA lt_external_data TYPE zrefx_ecc_vendor_f4h=>tyt_f_4_search_help. "SCM type
          DATA lt_external_data TYPE zrefx_ecc_vendor_details=>tyt_vendor_details. "SCM type
          DATA lt_result_data   TYPE TABLE OF zrefx_i_CLAIMS_vendor_f4. "Custom Entity type
          DATA lt_paged_entity  TYPE TABLE OF zrefx_i_CLAIMS_vendor_f4. "Custom Entity type

          lo_response->get_business_data( IMPORTING et_business_data = lt_external_data ).

          " Manual mapping of ECC structure to Custom Entity fields
**          lt_result_data = VALUE #( FOR rs IN lt_external_data (
**              Field  = 'VENDOR'
**              Value1 = rs-value_1
**              Descr1 = rs-descr_1
**          ) ).

          lt_result_data = CORRESPONDING #( lt_external_data MAPPING
                                          Vendorid             = vendor_id
                                          Vendorname           = vendor_name
                                          Vendorcompanyname    = vendor_company_name
                                          Contactpersonname    = contact_person_name
                                          Contactmobile        = vendor_mob_number
*                                Vendoraltnum         = vendor_alt_num
                                          Vendorregistrationno = vendor_reg_num
                                          Contactemail         = vendor_email_id
*                                Preferredlanguage    = preferred_language
                                          Vendoraddress        = vendor_address ).

          " 9. Send response back to the UI
          IF io_request->is_total_numb_of_rec_requested( ).
            io_response->set_total_number_of_records( lines( lt_result_data ) ).
          ENDIF.

          DATA(lv_top)  = io_request->get_paging( )->get_page_size( ).
          DATA(lv_skip) = io_request->get_paging( )->get_offset( ).

          IF lv_top > 0 AND lv_top <> if_rap_query_paging=>page_size_unlimited.
            " Calculate the slice boundaries
            DATA(lv_start) = lv_skip + 1.
            DATA(lv_end)   = lv_skip + lv_top.

            " Manually extract only the requested rows
            LOOP AT lt_result_data ASSIGNING FIELD-SYMBOL(<fs_row>)
                 FROM lv_start TO lv_end.
              APPEND <fs_row> TO lt_paged_entity.
            ENDLOOP.

            " Return the safely sliced data to RAP
            io_response->set_data( lt_paged_entity ).

          ELSE.
            " Return all data if no specific top size was requested
            io_response->set_data( lt_result_data ).
          ENDIF.

*          io_response->set_data( lt_result_data ).

        CATCH cx_http_dest_provider_error INTO DATA(lx_dest).
          " Error if destination 'refx_gw_ba' is missing in BTP Cockpit
          RAISE SHORTDUMP lx_dest.
        CATCH cx_web_http_client_error INTO DATA(lx_http).
          " Error with network or Cloud Connector connection
          RAISE SHORTDUMP lx_http.
        CATCH /iwbep/cx_gateway INTO DATA(lx_proxy).
          " Error mapping OData results
          RAISE SHORTDUMP lx_proxy..
          "handle exception
        CATCH cx_rap_query_filter_no_range.
          "handle exception
      ENDTRY.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
