@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Request for GL'
@Metadata.ignorePropagatedAnnotations: true
@Metadata.allowExtensions: true
@ObjectModel.semanticKey: ['RequestId']
define root view entity ZREFX_I_GL_REQUEST
  as select from zrefx_gl
  association [1] to ZREFX_DOV_CITY                 as _City       on $projection.City = _City.Value
  association [1] to ZREFX_DOV_STATUS               as _StatusText on $projection.Statuscode = _StatusText.Value
  composition of many ZREFX_I_GL_REQUEST_ATTACHMENT as _RequestAttachments
  composition of many ZREFX_I_GL_WORKFLOW_INSTANCE  as _WorkflowInstance
  composition of many ZREFX_I_GL_SITEVISIT          as _SiteVisit
{
  key request_id                 as RequestId,
      requestdate                as Requestdate,
      requesttype                as Requesttype,
      requestdescription         as Requestdescription,
      requestpurpose             as Requestpurpose,
      initiatorid                as Initiatorid,
      initiatorfullname          as Initiatorfullname,
      initiatororganization      as Initiatororganization,
      employeenumber             as Employeenumber,
      emailaddress               as Emailaddress,
      contactnumber              as Contactnumber,
      businessjustification      as Businessjustification,
      @ObjectModel.text.association: '_StatusText'
      statuscode                 as Statuscode,
      currentstep                as Currentstep,
      currentstepchangedat       as Currentstepchangedat,
      approvalstatuscode         as Approvalstatuscode,
      approvalstatus             as Approvalstatus,
      currentprocessorrole       as Currentprocessorrole,
      currentprocessoruser       as Currentprocessoruser,
      priority                   as Priority,
      sourcesubsidiary           as Sourcesubsidiary,
      sourcedepartment           as Sourcedepartment,
      requestor                  as Requestor,
      initiatedbyrole            as Initiatedbyrole,
      companycode                as Companycode,
      businessarea               as Businessarea,
      profitcenter               as Profitcenter,
      estimatedprojectcost       as EstimatedProjectCost,
      costcenter                 as Costcenter,
      projectname                as Projectname,
      projectname_a              as ProjectnameA,
      wbsprojectno               as Wbsprojectno,
      stagegateprojectno         as Stagegateprojectno,
      externalprojectaccountno   as Externalprojectaccountno,
      projectbudgetyear          as Projectbudgetyear,
      projectapprovalyear        as Projectapprovalyear,
      projectcostsar             as Projectcostsar,
      projectstartdate           as Projectstartdate,
      projectenddate             as Projectenddate,
      hijristartdate             as Hijristartdate,
      hijrienddate               as Hijrienddate,
      plancompletiondate         as Plancompletiondate,
      actualcompletiondate       as Actualcompletiondate,
      stationtype                as Stationtype,
      voltagekv                  as Voltagekv,
      capacitymva                as Capacitymva,
      cablelengthkm              as Cablelengthkm,
      facilitytype               as Facilitytype,
      landcategory               as Landcategory,
      widthmrequested            as Widthmrequested,
      lengthmrequested           as Lengthmrequested,
      areasqmrequested           as Areasqmrequested,
      gislocationlink            as Gislocationlink,
      gisprojectid               as Gisprojectid,
      gisdrawing                 as Gisdrawing,
      previousrequestno          as Previousrequestno,
      requestorcomments          as Requestorcomments,
      additionalcomments         as Additionalcomments,
      department                 as Department,
      userid                     as Userid,
      username                   as Username,
      sitearea                   as Sitearea,
      @ObjectModel.text.association: '_City'
      city                       as City,
      othercity                  as Othercity,
      region                     as Region,
      govtauthority              as GovtAuthority,
      requireddate               as RequiredDate,
      //      _StepMilestone.Description as CurrentStepDesc,
      title                      as Title,
      currentstepdescription     as Currentstepdescription,
      currentprocessorname       as Currentprocessorname,
      currentprocessordepartment as Currentprocessordepartment,
      milestone                  as Milestone,
      //      _Milestone.Description     as MileStoneDescription,
      milestonedesc              as Milestonedesc,
      workflowinstanceid         as Workflowinstanceid,
      //      milestonesequence          as Milestonesequence,
      //      _Milestone.Sequence        as MilestoneSequence,

      confirminformation         as ConfirmInformation,
      consentdate                as ConsentDate,
      req_org                    as RequestorOrg,
      req_org_text               as RequestorOrgText,
      req_org_text_a             as RequestorOrgAText,
      re_division_org            as REDivOrg,
      re_division_text           as REDivOrgText,
      re_division_text_a         as REDivOrgAText,
      re_reviewer                as REReviewer,
      re_reviewer_email          as RERevEmail,
      req_focal_point            as REQFocalPoint,
      req_focal_point_email      as REQFocalPointEmail,

      _RequestAttachments,
      _WorkflowInstance,
      _SiteVisit,
      _City,
      _StatusText
}
